### ISSUE TITLE
OpenVPN not working

### ISSUE THREAD

**Issue by ikzk** [katherlee/ustcaf-vpn-doc#1]
Continue `waiting for server reply` till timeout.

Tested on android with the recommended client.

**Comment by katherlee** [comment]
膜廉神！
OpenVPN connections from outside of China has been disabled since the international connections are heavily censored. It is only allowed to connect from client in China to the server which is also in China. PPTP should work fine everywhere.

**Comment by ikzk** [comment]
被发现了

Thanks, gonna close the issue (BTW, it might be better to mention this in the document).
